"""Shared figure style for ALL AC-RFT reports — the single source workers import so every plot matches.

This is the house convention (acrft_ogbench / Seohong Park paper style). Every figure in a report is
generated by a SCRIPT through this module (never a one-off hand drawing), so figures and data can
never drift. Import and call ``use()`` before plotting.

Convention (also documented in the Space RULES.md §4):
  * white background; only a light Y-grid (#e6e5e1, lw 0.7); top+right spines removed.
  * palette below — blue is primary; EVERY colour's meaning is stated in the legend/colorbar.
  * lines lw 2; uncertainty as a shaded CI band (``band()``) or error bars.
  * reference levels: dotted grey line via ``baseline()``, labelled inline (not a legend entry).
  * titles are VERY short and regular weight (never bold); conditions/n/protocol go in the prose
    and the spec table, not the title.
  * legend frameless; export at dpi 200 on white via ``save()``.

    import report_style as rs; rs.use()
    fig, ax = plt.subplots(figsize=rs.FIGSIZE)
    rs.band(ax, steps, mean, std, color=rs.BLUE, label="v3 (dist-V)")
    rs.baseline(ax, 0.26, "VLA baseline")
    ax.set_title("OpenDrawer success"); ax.legend()
    rs.save(fig, "fig.png")
"""

import matplotlib as mpl

# house palette (acrft_ogbench). Blue primary; each colour must be legend-explained in the figure.
BLUE = "#2a78d6"
GREEN = "#008300"
ORANGE = "#eb6834"
RED = "#c0392b"
PURPLE = "#7c3aed"
TEAL = "#0e7490"
GRAY = "#7a7a76"  # reference / baseline lines
GRID = "#e6e5e1"
INK = "#0b0b0b"
PALETTE = [BLUE, ORANGE, GREEN, RED, PURPLE, TEAL]

FIGSIZE = (6.4, 4.2)
DPI = 200


def use():
    mpl.rcParams.update(
        {
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
            "figure.figsize": FIGSIZE,
            "figure.dpi": DPI,
            "savefig.dpi": DPI,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.edgecolor": "#666666",
            "axes.linewidth": 0.9,
            "axes.labelcolor": INK,
            # a title is a label, not a sentence: short, regular weight. Every caveat goes in prose.
            "axes.titlesize": 11,
            "axes.titleweight": "normal",
            "axes.labelsize": 10.5,
            # only the horizontal grid, faint
            "axes.grid": True,
            "axes.grid.axis": "y",
            "grid.color": GRID,
            "grid.linewidth": 0.7,
            "xtick.color": INK,
            "ytick.color": INK,
            "xtick.labelsize": 9.5,
            "ytick.labelsize": 9.5,
            "font.family": "sans-serif",
            "font.sans-serif": ["DejaVu Sans", "Helvetica", "Arial"],
            "axes.unicode_minus": True,
            "legend.frameon": False,
            "legend.fontsize": 9,
            "axes.prop_cycle": mpl.cycler(color=PALETTE),
        }
    )


def band(ax, x, mean, std, *, color=BLUE, label=None, lw=2, alpha=0.15):
    """A mean line with a shaded ±std confidence band (the house uncertainty style)."""
    import numpy as np

    mean, std = np.asarray(mean), np.asarray(std)
    ax.plot(x, mean, color=color, lw=lw, label=label, zorder=3)
    ax.fill_between(x, mean - std, mean + std, color=color, alpha=alpha, lw=0, zorder=2)


def baseline(ax, y, label=None, *, color=GRAY):
    """A dotted grey reference level, labelled inline at the right edge (not a legend entry)."""
    ax.axhline(y, color=color, ls=":", lw=1.5, zorder=1)
    if label:
        ax.text(
            0.995,
            y,
            " " + label,
            color=color,
            fontsize=8.5,
            ha="right",
            va="bottom",
            transform=ax.get_yaxis_transform(),
        )


def save(fig, path):
    """Export white, tight, at the house dpi."""
    fig.savefig(path, dpi=DPI, bbox_inches="tight", facecolor="white")
